"""Reviewed business projector adapters generated by the event pipeline scaffolder.

Scaffolded handlers must fail closed until a real Inbox-transaction implementation
and PostgreSQL/JetStream end-to-end proof are added.
"""
